# Generated by Django 5.2.8 on 2025-11-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(blank=True, max_length=128, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "is_student",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("pesel", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "pesel_urk",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("workplace", models.CharField(blank=True, max_length=128, null=True)),
                ("pit_2", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "working_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pracujący", "0080004D"),
                            ("Zwolniony", "FFA5004D"),
                            ("Umowa o prace", "0000FF4D"),
                            ("Zmiana stanowiska", "FFFFFF4D"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("additional_information", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_name", "pesel"],
                        name="main_employ_last_na_28833e_idx",
                    ),
                    models.Index(
                        fields=["workplace", "last_name"],
                        name="main_employ_workpla_4528f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(blank=True, max_length=128, null=True)),
                ("number", models.CharField(blank=True, max_length=128, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("o_prace", "Umowa o pracę"),
                            ("zlecenia", "Umowa zlecenia"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("viber", "Viber"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(blank=True, max_length=128, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_submissions",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_period",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sanepid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=128, null=True)),
                ("doc_type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanepids",
                        to="main.employee",
                    ),
                ),
            ],
        ),
    ]
