# Generated by Django 5.2.8 on 2025-11-29 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taken_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workpermit",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_permits",
                to="main.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_type", "number"], name="main_docume_doc_typ_aa32ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["valid_until"], name="main_docume_valid_u_5035d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["value"], name="main_contac_value_968856_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentperiod",
            index=models.Index(
                fields=["employee", "start_date"], name="main_employ_employe_a66053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employmentperiod",
            index=models.Index(
                fields=["employee", "end_date"], name="main_employ_employe_b4fdce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "created_at"], name="main_task_status_ed0661_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="main_task_assigne_96dc91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["taken_by", "status"], name="main_task_taken_b_faff93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workpermit",
            index=models.Index(
                fields=["doc_type", "end_date"], name="main_workpe_doc_typ_7f86c0_idx"
            ),
        ),
    ]
