# Generated by Django 5.2.8 on 2025-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
