# Generated by Django 5.2.8 on 2025-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_history_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="student_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sanepid",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
