# Generated by Django 5.2.8 on 2025-12-05 16:48

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_files/group/"
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.chat.models.message_file_path
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
